### ISSUE TITLE
Sitemap.xml always empty

### ISSUE THREAD

**Issue by WizX20** [CorteXodus/SC72_XML_Sitemap_Generator#1]
Just tried this one, installed the package and configured the config.include file. Then generated the sitemap.xml from the new sitemap menu in sitecore: No succes. The file is always empty no matter what I try. I haven't been able to tackle this yet, but I could not find anything in the sitecore log files.

**Comment by CorteXodus** [comment]
My first guess is that you haven't added any templates to the Sitemap Manager's settings item. In the Sitecore tree, under 'System' -> 'Modules', there should be an item called "SitemapSettings". That item contains a field for including the templates which should be evaluated when producing the sitemap. I think I've probably spit out dozens of sitemaps that were empty after forgetting to populate that thing!
